$ANSIBLE_VAULT;1.1;AES256
32303938636162303733336536306333366565343163373564666661313661313930666639643532
6634393637343765643331356237663034343761633662620a383162636665633963376464343765
36383439646461353036653530303564323465303365303565393831336635623538393033326339
6564323231666663330a613535613337366435396462333436303530336132626164623936626563
31636434333639316133396565613161353032653737323365356331613335313535306630336466
31636238643238343033663163303235626534626637303034346366653331613936353239393039
61666662313862623165343238353461643961326163386263303465383064343039336161623339
66326432343832333031353738376434663836316565343131613962633333333065376265303934
34333465393835303538393461373563383635386338306339306436663534646564373061643763
33383634303538303739383939636231383635333533316336663936616633646462326261616336
646563313362326362356139393437666564
