all:
  children:
    nfs_servers:
      hosts:
        nfs-server:
          ansible_host: 192.168.1.220
    ai_commanders:
      hosts:
        ai-commander:
          ansible_host: 192.168.1.221
    reverse_proxies:
      hosts:
        reverse-proxy:
          ansible_host: 192.168.1.225
