---
- name: nfs-common のインストール
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: NFS マウント (fstab 永続化)
  ansible.posix.mount:
    src: "{{ nfs_mount_src }}"
    path: "{{ nfs_mount_dest }}"
    fstype: nfs
    opts: "{{ nfs_mount_opts }}"
    state: mounted
